### ISSUE TITLE
Zoom und Schließen Buttons erscheinen nicht 

### ISSUE THREAD

**Issue by MrMusic** [Erftralle/JoomGalleryPhotoSwipePlugin#1]
Hi Erftralle,
auf einem uralt 3,5 Zoll Smartphone als auch einem 7 Zoll Tablet erscheinen rechts oben die Buttons nicht (mit chrome und firefox getestet). Auf einem Desktop Rechner erscheinen die Buttons korrekt. Kann man da etwas machen?
Viele Grüße
Alwin

**Comment by Erftralle** [comment]
Hi Alwin,
der Zoom-Button ist eigentlich ein Vollbild-Button ;-) .
Auf einem Android 4.4.4  Smartphone (5 Zoll) mit aktuellem FF funktioniert es bei mir zunächst. Erst nachdem man einmal den Vollbild-Button betätigt hat, erscheinen die Buttons nicht mehr, allerdings auch der Bildzähler oben links nicht mehr.
Mit Chrome werden die Buttons gar nicht angezeigt, das kann ich bestätigen.
Eigentlich sollten sie aber angezeigt werden, die Optionen hierfür sind auf jeden Fall standardmäßig aktiviert.

Da es sich hierbei um Probleme im PhotoSwipe selbst handelt, kann ich da leider nicht helfen (jedenfalls nicht, ohne mich vorher intensiv mit dem PhotoSwipe Skript auseinanderzusetzen) . Wenn du Lust hast, kannst du ja bei [PhotoSwipe](https://github.com/dimsemenov/PhotoSwipe) mal ein Issue aufmachen.

**Comment by Erftralle** [comment]
Nach genauerem Hinsehen scheint es doch an der JoomGallery selbst zu liegen.

An vielen Stellen ist die JoomGallery noch nicht Responsive genug für kleinere Displays. In der Kategorieansicht z.B. führt es bei der Anzeige der Sortierfunktionen, bei der Detailansicht z.B. bei der Anzeige der Minis zu Overflows, die PhotoSwipe dann einen zu großen Viewport anzeigen. Dies hat diverse Probleme bei der Anzeige von PhotoSwipe zur Folge.

Wenn ich aber diese Optionen in der JoomGallery bei mir deaktiviere (Sortierfunktion, Minis), gibt es keine Probleme mit der Anzeige der Buttons.

**Comment by Erftralle** [comment]
Möglicherweise liegt es aber auch daran, dass eine bestimmte SVG Datei, die zur Anzeige der Toolbar bei einigen Browsern benötigt wird, in der Manifest Datei des Plugins fehlte ;-) .
Dies sollte mit der Version v1.2 des Plugins behoben sein.

**Comment by Chraneco** [comment]
Kann ich bestätigen, vielen Dank!

**Comment by MrMusic** [comment]
Funktioniert mt der neuen Version Prima. Danke! :thumbsup:

**Comment by Erftralle** [comment]
Thanks for your feedback :-) .
