### ISSUE TITLE
Falsche Zentrierung, Slideshow & Bilder Download

### ISSUE THREAD

**Issue by imperialo** [Erftralle/JoomGalleryPhotoSwipePlugin#10]
Hallo Erftralle,

1. Ich wollte mal fragen, wenn man das iPhone dreht, wird das Bild nicht zentriert dargestellt sondern als Liste (also 3 auf einmal).
2. Ist es möglich eine Slideshow zu starten?
3. Beim orginal Photoswipe kann man beim Pfeil noch das Bild downloaden - bei dir auch möglich?

Sonnige Grüße

Impi

**Comment by Erftralle** [comment]
Hallo,

> Ich wollte mal fragen, wenn man das iPhone dreht, wird das Bild nicht zentriert dargestellt sondern als Liste (also 3 auf einmal).

Dies hat möglicherweise etwas mit dem in dem Issue dimsemenov/PhotoSwipe#1315 behandeltem Problem bzw. Bug in iOS 10.3 zu tun.

> Ist es möglich eine Slideshow zu starten?

Nein, im derzeitigen PhotoSwipe Skript ist keine Slideshow vorgesehn.

> Beim orginal Photoswipe kann man beim Pfeil noch das Bild downloaden - bei dir auch möglich?

Nein, habe ich bis jetzt noch nicht implementiert.

**Comment by Erftralle** [comment]
@imperialo :

Ich habe gerade eine neue Version veröffentlicht (v1.6). Sie beinhaltet die aktuelle Version des PhotoSwipe Skripts, die einen Workaround für den Bug in iOS 10.3 enthält. Vielleicht löst dieser dein Problem ebenfalls.

Zudem gibt es jetzt auch einen Download Link in den Share Elementen, vorausgesetzt du hast den Download auch in der JoomGallery Konfiguration freigeschaltet.

**Comment by Erftralle** [comment]
@imperialo 

Ich habe gerade eine neue Version veröffentlicht (v1.7). Sie enthält jetzt auch eine simple Slideshow.

**Comment by imperialo** [comment]
@Erftralle 

einfach nur perfekt! :+1: 

Vielen Dank

**Comment by Erftralle** [comment]
Vielen Dank!

Ich schließe dann hier mal.
