### ISSUE TITLE
W3C error caused by wrong rel attribute

### ISSUE THREAD

**Issue by ThiloSO** [Erftralle/JoomGalleryPhotoSwipePlugin#12]
Hi there, it's not really a functional problem - but it would be nice to get the plugin running without w3c errors.

Right now w3c shows up with:

Error: Bad value "PhotoSwipe-v4plus-joomgallery" for attribute "rel" on element "a": The string "PhotoSwipe-v4plus-joomgallery" is not a registered keyword.

Any chance to get this fixed somehow?

**Comment by Erftralle** [comment]
Thanks for the hint!

Please change line **278** of **plugins/joomgallery/photoswipe/photoswipe.php** to

`
    $attribs['data-rel']     = $this->title.'-'.$group;
`

and line **61** of **media/plg_joomgallery_photoswipe/jg-photoswipe.js** to

`
    $("a[data-rel^='PhotoSwipe-v4plus']").on("click", function(event) {
`

and check the result.  

Please also check if you find any backward compatibility problems with that change.

**Comment by ThiloSO** [comment]
Nice!
Works well - installed it on two different setups and i can't see any compatibility problems.

Thanks so much!

**Comment by Erftralle** [comment]
Thanks for testing and your feedback. Released a new version just now.
