### ISSUE TITLE
Non-mobile opening - Exception for Detail View

### ISSUE THREAD

**Issue by toby07801** [Erftralle/JoomGalleryPhotoSwipePlugin#2]
I have a question (and perhaps a suggestion for the future) on how I can achieve a certain behaviour. 

The plugin has the "Non-mobile opening" option set to "Default View" as I want my desktop users to be able to reach the Detail view and my mobile users to open images straight in Photoswipe from the category thumbnails page.

However, once desktop users have reached the Detail view, I would like them to be able to open the image in Photoswipe from there - this is now impossible though because the plugin is set to open "Default View" on Desktops - so when the button is clicked it bounces me back to the current Detail view page once again.

I'm guessing the code that controls this is in your photoswipe.php on line 173, at least playing with that earlier changed the behaviour - Is there any way you can suggest that I can add in an extra bit of code (an exception so to speak) that allows the opening of Photoswipe on Desktops only if the current page is the JoomGallery Detail view, regardless of the plugin setting?

Many thanks for any suggestions! Keep up the great work!

**Comment by Erftralle** [comment]
Thanks for reporting this issue.
The latest commits should do the trick.

**Comment by toby07801** [comment]
Fantastic! Now it works! Thank you! :+1:

**Comment by Erftralle** [comment]
Thanks for your feed back.
