### ISSUE TITLE
View Counter

### ISSUE THREAD

**Issue by toby07801** [Erftralle/JoomGalleryPhotoSwipePlugin#3]
Not sure what you can do about it from this plugin as I suspect the functionality is part of the main JoomGallery component and has been around for years but I thought I'd just mention the fact that the previous/next image pre-loading functionality of Photoswipe still increases the hits counters of both neighbouring images, even if they were not actually viewed.

This then has the unwanted effect that it skews the Toplists, i.e. an unpopular image which happens to sit next in sequence to a highly popular image will also move up the Toplist ranks due to being constantly pre-loaded by Photoswipe, even if hardly anybody has actually viewed it.

**Comment by Erftralle** [comment]
The only way I know to tackle with this problem would be to disable the image preloading in the PhotoSwipe script which is unfortunately not possible (see [PhotoSwipe options](http://photoswipe.com/documentation/options.html)).
If you like you can open a feature request at the [PhotoSwipe issue tracker](https://github.com/dimsemenov/PhotoSwipe/issues).

**Comment by toby07801** [comment]
Thanks, but I suppose that wouldn't make sense for the photoswipe developers to implement since it is generally a useful feature.
