### ISSUE TITLE
Duplicates in PhotoSwipe

### ISSUE THREAD

**Issue by toby07801** [Erftralle/JoomGalleryPhotoSwipePlugin#4]
I noticed that when you provide a number of different ways to open an image in PhotoSwipe on the Detail page, such as in my case via: A) the linked image itself, B) a standalone button below the image and C) a hover overlay on the image (which one is shown depends responsively on the device / screen size used) I end up with duplicates of that image in PhotoSwipe (the duplicates appear when swiping backwards) and then the rest of the images in that category appear normally. The number of duplicates seems to correspond to the number of links to PhotoSwipe provided on that page.

Is there any way to include a check for duplicates and if there are any just load the link once?

**Comment by Erftralle** [comment]
To be honest, I don't know exactly what you mean.
Your mentioned ways to open an image (B and C) are not included in an unmodified standard JoomGallery installation.

Please provide a link showing the problem on desktop browsers.

**Comment by toby07801** [comment]
Sorry I guess a live example would help! And yes you are right, this isn't a 100% out of the box page, but I believe even a JoomGallery default installation can have the image linked AS WELL as the option of a Zoom button under the image - which is what I have hijacked - making two links.

To see this in action please go to this link http://bit.ly/1FgmS2x 

You'll find a hover overlay on the image in the top right corner to go into PhotoSwipe, as well as a button under the image. (For smaller screens the overlays and buttons disappear and just the image itself becomes the link to go into PhotoSwipe) 

To use that functionality you will first need to log in though! 
user: testuser / pw: erftralle

Use one of the two buttons to get into PhotoSwipe.

Now swipe backwards and you will see two further copies of the same image before the next one appears. Swiping forwards is ok.

Hope that helps!

**Comment by Erftralle** [comment]
After visiting your site I understand your problem.

> ... but I believe even a JoomGallery default installation can have the image linked AS WELL as the option of a Zoom button under the image ...

That's true, but you would not find any duplicates when opening PhotoSwipe by using JoomGallery out of the box ;-) . JoomGallery takes care of this by using different `rel` and `data-group` attributes for the different links and provides all links twice, first for the image link itself with `data-group=joomagallery` and second for the zoom icon with `data-group=joomagalleryIcon`.

Your modifications all use `rel=PhotoSwipe-v4plus-joomgallery` and `data-group=joomagallery` so that the actual detail image will be pushed 3 times to PhotoSwipe. If you would have modified you zoom button below the detail image to use `rel=PhotoSwipe-v4plus-joomgalleryIcon` and `data-group=joomagalleryIcon` there would be one problem less (btw. all the links with `data-group=joomagalleryIcon` on your detail view are useless now).

But would leave the problem with the overlay on the image. You could modify the JoomGallery source code to cope with that problem which would mean to have a third group and the need to provide all image links a third time.

An alternative solution would be to modify the source of **/media/plg_joomgallery_photoswipe/jg-photoswipe.js**.

Replace lines 72-76 with the following code

```
        var indexDuplicate = -1;
        if(true) { // TODO Plugin option
          for (var i = 0; i < items.length; i++) {
            if (items[i].src === item.src) {
              indexDuplicate = i;
              break;
            }
          }          
        }

        if(indexDuplicate == -1) {
          items.push(item);

          if(item.src === href) {
            index = items.length - 1;
          }
        }
        else {
          if(items[indexDuplicate] == href) {
            index = indexDuplicate;
          }
        }
```

and check if this works for you. Maybe later on we could add an additional option to the plugin parameters as there might be people who want to use duplicates.

**Comment by toby07801** [comment]
Thanks a lot for the detailed reply. That makes sense. I just copied the existing zoombutton and naively thought this would just provide another way to open PhotoSwipe. Duh!

The modification to jg-photoswipe.js you suggested above works perfectly for me! I've got no more duplicates and the image counter in the top-left corner shows the correct number! I'd say it's probably unlikely that people would deliberately want duplicates in their swipe gallery so perhaps it's even a useful addition.

What's the reason by the way that you have taken out the share functionality that came with PhotoSwipe?

I hope you enjoyed my detail image navigation customisations by the way. Ever since Google's recent "Mobilegeddon" I've also tried as best I could to make my whole JoomGallery as close to responsive as I could (I guess the correct terms is adaptive here) which I found only really worked by setting all column settings in the JoomGallery configuration to just one so each .jg_row contains just one item and then using CSS to float them into rows of three, two or one depending on the screen width. Kind of works for now, not sure if you guys are already working on a responsive gallery for the next release?

Anyway, I digress, thanks again for the fantastic help with the above!

**Comment by Erftralle** [comment]
> The modification to jg-photoswipe.js you suggested above works perfectly for me! I've got no more duplicates and the image counter in the top-left corner shows the correct number!

Thanks for your feedback.

> I'd say it's probably unlikely that people would deliberately want duplicates in their swipe gallery so perhaps it's even a useful addition.

I think you are right and I decided to implement a slightly different snippet in the plugin (without a plugin option).

> What's the reason by the way that you have taken out the share functionality that came with PhotoSwipe?

No special reason. I don't use and like shares and you are the first asking for it ;-) . You will find a new plugin option for it now.

> I hope you enjoyed my detail image navigation customisations by the way.

To be honest, I just had a quick look at your site to identify the problem you had, but what I saw so far was quite good.

> Kind of works for now, not sure if you guys are already working on a responsive gallery for the next release?

This is a question to be answered by the JoomGallery project team :-) .

**Comment by toby07801** [comment]
Thank you, I've given it a test-drive and all seems to work well! Great to see it come out of BETA too. This plugin is miles better than the original PhotoSwipe that was available for JoomGallery! Nice work! :)

**Comment by toby07801** [comment]
Having said that, a slight issue with the sharer seems to be that it always links to the first image that was opened, not the current image, if a user has advanced a few images in the sequence and wants to share an image it doesn't work.

I suppose the only way to fix that is to use the current image ID which we have and then use the 'ugly' URL to link to its detail page, something like... 

```
 var detail_url = encodeURIComponent("http://xxxxx.xx/index.php?option=com_joomgallery&Itemid=xxx&view=detail&id=" + current_img_id);
```

In combination with a feature I suggested to Joomgallery yesterday (https://github.com/JoomGallery/JoomGallery/issues/23) and which I have used for a couple of years now the social media sites will be able to translate that ugly URL back to the pretty URL using the canonical tag.

**Comment by Erftralle** [comment]
Thanks for your feedback.

Would you mind to open a separate issue for the problem with the sharer. I would like to close this issue (called **Duplicates in PhotoSwipe**) because the problem with duplicates is resolved now.

Thanks in advance.

**Comment by toby07801** [comment]
No problem, will do!
