### ISSUE TITLE
Sharing of current image is not reliable in the case of an image sequence

### ISSUE THREAD

**Issue by toby07801** [Erftralle/JoomGalleryPhotoSwipePlugin#5]
A slight issue with the sharer seems to be that it always links to the first image that was opened, which is not necessarily the current image if a user has advanced a few images in the sequence and it could also be the Category page if used from a mobile and Detail view is skipped. So if you want to share the image you're looking at it doesn't work reliably.

One possible way to fix that could be to use the JoomGallery Image ID of the current image which would be fairly easy to obtain and then use the 'ugly' Joomla URL to share a link to the image's detail page, which would look something like...

```
 http://yourdomain.com/index.php?option=com_joomgallery&Itemid=xxx&view=detail&id=current_image_id
```

This would require the user to first fill in their domain and the JoomGallery Item ID as a parameter however.

In combination with a feature I suggested to Joomgallery (https://github.com/JoomGallery/JoomGallery/issues/23) - which I have successfully used for a couple of years now - any social media sites which would receive this 'ulgy' URL would be able to translate and associate that back to the 'pretty' URL by making use of the rel=canonical tag.

**Comment by Erftralle** [comment]
Thanks for opening this as a separate issue.

What do you think is not working reliably seems to be more of that kind, that you are expecting something else from the share functionality.

For me it is reliably that URL shared, from which the PhotoSwipe box has been opened, so it is the detail view, the category view or any other view where the content plugin or a JoomGallery module is used and configured to use the PhotoSwipe plugin.

See **media/plg_joomgallery_photoswipe/photoswipe-ui-default.js** line 89ff

```
getPageURLForShare: function( /* shareButtonData */ ) {
        return window.location.href;
},
```

However, you could adapt that behaviour to your personal needs.

E.g. for the Facebook share:
If you want to share the image URL directly you could change **media/plg_joomgallery_photoswipe/jg-photoswipe.js** line 103 to

```
 {id:'facebook', label:'Share on Facebook', url:'https://www.facebook.com/sharer/sharer.php?u={{image_url}}'},
```

By replacing `url` with `image_url` now

```
getImageURLForShare: function( /* shareButtonData */ ) {
    return pswp.currItem.src || '';
},
```

is used as the URL for sharing (see **media/plg_joomgallery_photoswipe/photoswipe-ui-default.js** line 86ff). See also http://photoswipe.com/documentation/options.html for detailed information.

**Comment by toby07801** [comment]
I suppose it works reliably in that it shares the current url which may be what you want. It's just not necessarily a direct link to the image.

I've managed to add the download function to the share buttons  by adding 
     {id:'download', label:'Download image', url:'{{raw_image_url}}', download:true}

This seems to reliably download the image that is currently displayed, with its watermark as it should.

I am a bit lost in this though, could you help me by pointing me in the right direction to make the share url the link to the detail page of whatever image is currently open?

Essentially I need the share link to look like this:
    http://mydomain.com/index.php?option=com_joomgallery&Itemid=xxx&view=detail&id="JoomGalleryImageID"

Where would I configure this?

**Comment by toby07801** [comment]
Basically I'm stuck at this point: 
I've modified **photoswipe.php** to get the Image ID passed as an attribute

```
// Prepare the link attributes
$attribs['rel']          = $this->title.'-'.$group;
$attribs['data-group']   = $group;
$attribs['data-title']   = $data_title;
$attribs['data-size']    = $data_size;
// Add JoomGallery Image ID to attributes
$attribs['img-id']       = $image->id;
```

In **jg-photoswipe.js** I've added on line 71

```
  $('a[data-group=' + $(this).attr('data-group') + ']').each(function() {
    size = $(this).attr('data-size').split('x');
    var item = {
      src: $(this).attr('href'),
      w: parseInt(size[0], 10),
      h: parseInt(size[1], 10),
      title: $(this).attr('data-title'),
      id: $(this).attr('img-id')
    };
```

But I can't seem to change the share buttons {{url}} bit without the thing breaking somehow. 

How do I get _http://mydomain.com/index.php?option=com_joomgallery&Itemid=xxx&view=detail&id=_ + the id from above into the {{url}} part of the ShareButtons?

```
    shareButtons: [
                   {id:'facebook', label:'Share on Facebook', url:'https://www.facebook.com/sharer/sharer.php?u={{url}}'},
                   {id:'twitter', label:'Tweet', url:'https://twitter.com/intent/tweet?text={{text}}&url={{url}}'}
                  ]    
```

**Comment by Erftralle** [comment]
Insert at line 249 in **photoswipe.php**

```
    $attribs['data-share']   = JRoute::_('index.php?option=' . _JOOM_OPTION . '&view=detail&id=' . $image->id . $this->_jg_ambit->getItemid(true));
```

Change lines 66 - 71 and 103 - 107 in **jg-photoswipe.js**

```
        var item = {
          src: $(this).attr('href'),
          w: parseInt(size[0], 10),
          h: parseInt(size[1], 10),
          title: $(this).attr('data-title'),
          share: $(this).attr('data-share')
        };
```

and

```
        shareButtons: [
                       {id:'facebook', label:'Share on Facebook', url:'https://www.facebook.com/sharer/sharer.php?u={{url}}'},
                       {id:'twitter', label:'Tweet', url:'https://twitter.com/intent/tweet?text={{text}}&url={{url}}'},
                       {id:'pinterest', label:'Pin it', url:'http://www.pinterest.com/pin/create/button/' + '?url={{url}}&media={{image_url}}&description={{text}}'}
                      ],
        getImageURLForShare: function( /* shareButtonData */ ) {
          return pswp.currItem.share || '';
        }
```

**Comment by toby07801** [comment]
Hi, thanks for that. That's sort of what I did, except I hard coded the first part of my URL whereas you're doing it properly via JRoute. 

However the problem with this (again) is that the link that gets shared is still the one that PhotoSwipe was opened from, not the link to the current image.

For example: 
- I go to one of my Detail pages which is part of a category with many images. 
- I open that image in PhotoSwipe, let's say it was the image with ID 100
- I swipe forwards a few times and am now looking at image ID 105. 
- I want to share that image I'm looking at so I press share.
- (I would expect the sharer to now share a link to the detail view of image ID 105) 
- However, the link that the sharer is passing to facebook is still the link to image ID 100, not 105...

Somewhere the {{url}} bit is always being replaced by the browsers current URL where I first opened PhotoSwipe, I just need to somehow pass it the url that we generated as the data-share attribute. 

Confused!

**Comment by Erftralle** [comment]
Sorry, my fault.

Change lines 103 - 107 in jg-photoswipe.js to

```
        shareButtons: [
                       {id:'facebook', label:'Share on Facebook', url:'https://www.facebook.com/sharer/sharer.php?u={{url}}'},
                       {id:'twitter', label:'Tweet', url:'https://twitter.com/intent/tweet?text={{text}}&url={{url}}'},
                       {id:'pinterest', label:'Pin it', url:'http://www.pinterest.com/pin/create/button/' + '?url={{url}}&media={{image_url}}&description={{text}}'}
                      ],
        getPageURLForShare: function( /* shareButtonData */ ) {
          return pswp.currItem.share || '';
        }
```

It must be `getPageURLForShare`, not `getImageURLForShare`.
With this change it is working in my tests.

**Comment by toby07801** [comment]
It's not working for me, the URL (for me at least) doesn't change while Photoswipe is open and I advance images. This latest edit behaves the same for me as the previous one, the link that gets shared is the first image that was opened...

I'll attach the contents of my file for you to see if there's an issue I'm missing:

```
(function(window, document, $, undefined) {
 $(document).ready(function(){ 

$('body').append('<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true"/>');
$(".pswp").append('<div class="pswp__bg"/>');
$(".pswp").append('<div class="pswp__scroll-wrap"/>');
$(".pswp__scroll-wrap").append('<div class="pswp__container"/>');
$(".pswp__container").append('<div class="pswp__item"/>');
$(".pswp__container").append('<div class="pswp__item"/>');
$(".pswp__container").append('<div class="pswp__item"/>');
$(".pswp__scroll-wrap").append('<div class="pswp__ui pswp__ui--hidden"/>');
$(".pswp__ui").append('<div class="pswp__top-bar"/>');
$(".pswp__top-bar").append('<div class="pswp__counter"/>');
$(".pswp__top-bar").append('<button class="pswp__button pswp__button--close" title="Close (Esc)"/>');
$(".pswp__top-bar").append('<button class="pswp__button pswp__button--share" title="Share"/>');
$(".pswp__top-bar").append('<button class="pswp__button pswp__button--fs" title="Toggle fullscreen"/>');
$(".pswp__top-bar").append('<button class="pswp__button pswp__button--zoom" title="Zoom in/out"/>');
$(".pswp__top-bar").append('<div class="pswp__preloader"/>');
$(".pswp__preloader").append('<div class="pswp__preloader__icn"/>');
$(".pswp__preloader__icn").append('<div class="pswp__preloader__cut"/>');
$(".pswp__preloader__cut").append('<div class="pswp__preloader__donut"/>');
$(".pswp__ui").append('<div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap"/>');
$(".pswp__share-modal").append('<div class="pswp__share-tooltip"/>');
$(".pswp__ui").append('<button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"/>');
$(".pswp__ui").append('<button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"/>');
$(".pswp__ui").append('<div class="pswp__caption"/>');
$(".pswp__caption").append('<div class="pswp__caption__center"/>');

$("a[rel^='PhotoSwipe-v4plus']").on("click", function(event) {

  var pswpElement = document.querySelectorAll('.pswp')[0];
  var pswp, options, items = [], index = 0;
  var href = $(this).attr('href');

  $('a[data-group=' + $(this).attr('data-group') + ']').each(function() {
    size = $(this).attr('data-size').split('x');
    var item = {
      src: $(this).attr('href'),
      w: parseInt(size[0], 10),
      h: parseInt(size[1], 10),
      title: $(this).attr('data-title'),
      /// Here's where I've added the data-share attribute line
      share: $(this).attr('data-share')
    };

    // Check for duplicates
    var isDuplicate = false;

    for (var i = 0; i < items.length; i++) {
      if (items[i].src === item.src) {
        isDuplicate = true;
        break;
      }
    }          

    if(!isDuplicate) {
      items.push(item);

      if(item.src === href) {
        index = items.length - 1;
      }
    }

  });

  options = {
    index: index,
    loop: jg_pswp_options.loop,
    history: false,
    shareEl: jg_pswp_options.shareEl,
    captionEl: jg_pswp_options.captionEl,
    closeOnScroll: false,
    escKey: true,
    arrowKeys : true,
    clickToCloseNonZoomable: false,
    shareButtons: [
                   {id:'facebook', label:'Share on Facebook', url:'https://www.facebook.com/sharer/sharer.php?u={{url}}'},
                   {id:'twitter', label:'Tweet', url:'https://twitter.com/intent/tweet?text={{text}}&url={{url}}'},
                   {id:'pinterest', label:'Pin it', url:'http://www.pinterest.com/pin/create/button/' + '?url={{url}}&media={{image_url}}&description={{text}}'}
                  ],
                  getPageURLForShare: function( /* shareButtonData */ ) {
                    return pswp.currItem.share || '';
                  }
  };

  pswp = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
  pswp.init();

  var photoswipe_onkeydownsave = window.document.onkeydown;
  window.document.onkeydown = null;

  pswp.listen('destroy', function() {
    window.document.onkeydown = photoswipe_onkeydownsave;
  });

  return false;
});
});
}(window, document, window.jQuery));
```

**Comment by toby07801** [comment]
Update: There might be seomtheing wrong with the attribute itself.

If I use an attribute called

```
 $attribs['detail-view']  = "http://mydomain.co.uk/index.php?option=com_joomgallery&Itemid=339&view=detail&id=".$image->id;
```

and then

```
 detail_view: $(this).attr('detail-view'),
```

and

```
 getPageURLForShare: function( /* shareButtonData */ ) {
                    return pswp.currItem.detail_view || '';
                  }
```

it works!!! :) But that's sort of hard coded except for the image id bit.

Yours reads:

```
 $attribs['data-share']   = JRoute::_('index.php?option=' . _JOOM_OPTION . '&view=detail&id=' . $image->id . $this->_jg_ambit->getItemid(true));
```

for some reason that always bounces me back to the first image on share.

Anyway I guess this is good enough for me! But let me know if you know why the other way doesn't seem to work.

**Comment by Erftralle** [comment]
Tested **your code** and it is working fine. 
Tested in latest Chrome and Firefox on desktop and latest Chrome on mobile.
Don't forget to clear your caches if using any.

**Comment by Erftralle** [comment]
Just saw that I did not get  your last post.
Just for clarification, what I tested was the code you posted in the post before.

**Comment by toby07801** [comment]
Got it working. Another small problem was also that you need to include the domain name in the facebook share URL. JRoute:: would just pass "/index.php?..." etc. and it won't work when passed to facebook like that. The other thing may have been a cache issue, not sure! I tried it all again using a different attribute name and it started working.

Thanks for the pointers and feel free to close the issue.

**Comment by Erftralle** [comment]
> Another small problem was also that you need to include the domain name in the facebook share URL. JRoute:: would just pass "/index.php?..." etc. and it won't work when passed to facebook like that. 

Does a change to

```
    $attribs['data-share']   = JUri::getInstance()->toString(array('scheme', 'host', 'port')) . JRoute::_('index.php?option=' . _JOOM_OPTION . '&view=detail&id=' . $image->id . $this->_jg_ambit->getItemid(true));
```

solve this problem?

**Comment by toby07801** [comment]
Yes, just tried the above and it works too - without hard-cording the domain and protocol. Thank you!

**Comment by Erftralle** [comment]
Thanks for your feedback.
I've implemented a new plugin otion to adjust the page URL to share.
