### ISSUE TITLE
Desktop Computer are Mobile Device?

### ISSUE THREAD

**Issue by brunnerimages** [Erftralle/JoomGalleryPhotoSwipePlugin#6]
The Photoswipe recognizes the Google Chrome not and also the mobile version. Is there a solution for this too?

Der Photoswipe erkennt leider den Google Chrome als Mobiles Gerät am Desktop PC. Kann man das irgendwie umgehen oder lösen?

Greetz Philipp

**Comment by Erftralle** [comment]
Sorry, but I can **not** confirm that.

I have configured my test case to use PhotoSwipe on mobile and Slimbox on non mobile devices for the detail view and it is working correctly.

Tested on desktop (Windows 7) with Chrome version 43.0.2357.81 m and on Android 4.4 with Chrome version 43.0.2357.92.

Maybe your plugin settings are not correct.
Please provide a link showing the problem.
Post screenshots of your plugin settings.
What are your versions (OS, Joomla!, Plugin, Browser etc. ...)

**Comment by Erftralle** [comment]
Since there was no reply I close this issue.
