### ISSUE TITLE
Share Buttons anpassen

### ISSUE THREAD

**Issue by derChristoph** [Erftralle/JoomGalleryPhotoSwipePlugin#7]
Ich benutze das Plugin super!

Ich würde gerne die Share Buttons anpassen.
So das z.B. Whatsapp auf mobilen Geräten dazukommt

Bzw. generell die Buttons erweitern.
Jemand ne Idee wie das geht?

**Comment by Erftralle** [comment]
> Ich würde gerne die Share Buttons anpassen.
> So das z.B. Whatsapp auf mobilen Geräten dazukommt

Versuch es mal mit folgenden kleinen Änderungen:
In der Datei **photoswipe.php** ersetze Zeile 123 mit den beiden Zeilen

```
    $options .= "  shareEl: ".$shareEl.",\n";
    $options .= "  isMobile: ".($this->_isMobile ? 'true' : 'false')."\n";
```

und in der Datei media/jg-photoswipe.js füge in Zeile 113 den Code

```
      if(jg_pswp_options.isMobile) {
        options.shareButtons.push({id:'whatsapp', label:'Share on WhatsApp', url:'whatsapp://send?text={{url}}'});
      }
```

hinzu.

Ich kann es selber leider nicht testen, da ich keinen WhatsApp Account habe und auch keinen anlegen möchte.

**Comment by derChristoph** [comment]
Super funktioniert! vielleicht kannst du es ja mit aufnehmen!

**Comment by Erftralle** [comment]
Danke für das Feedback, das Feature wird natürlich mit aufgenommen.

**Comment by Erftralle** [comment]
Das Feature ist nun in der neusten Version enthalten, ich schließe dann diesen Eintrag.
