### ISSUE TITLE
Titel / Caption

### ISSUE THREAD

**Issue by derChristoph** [Erftralle/JoomGalleryPhotoSwipePlugin#8]
Ich habe Bilder die haben im Dateinamen keine Typische namen wie: IMG_1560.JPG
Sondern einen Text.
Ich möchte gerne bei Bildern die ein Leerzeichen und länger als 12 Buchstaben sind das über dem Bild der Dateiname angezeigt wird.

Kannst du mir sagen wo ich ansetzten muss?

**Comment by Erftralle** [comment]
Ich bin mir nicht wirklich sicher, ob ich ich verstehe, was du meinst und willst.

Verwende doch die JoomGallery Option **Original-Dateiname**. Dann wird automatisch beim Upload eines Bildes der Dateiname als Bildtitel verwendet. Der kann dann bei entsprechender Konfiguration (JoomGallery + Plugin) unterhalb des Bildes angezeigt werden. Um sie oberhalb des Bildes anzuzeigen, musst du in der Datei **jg-photoswipe.js** (siehe Zeilen 33-56) entsprechende Anpassungen vornehmen.

Die Bildunterschrift wird im Plugin übrigens in der Datei **photoswipe.php** ab Zeile 220 zusammen gebaut. Hier könntest du eventuell manipulativ eingreifen.

**Comment by derChristoph** [comment]
genau die infos habe ich gebracht danke!

**Comment by Erftralle** [comment]
OK, dann schließe ich diesen Eintrag.
