### ISSUE TITLE
Allow description formatted

### ISSUE THREAD

**Issue by MrMusic** [Erftralle/JoomGalleryPhotoSwipePlugin#9]
Vorschlag: Formatierte Bildbeschreibung erlauben.
Unabhängig von der Einstellung im Konfigurations-Manager wird derzeit eine evtl. angezeigte Bildbeschreibung immer ohne Formatierung dargestelt.
Mit der folgenden Änderung der Zeile 241 sollte es möglich sein, eine formatierte Bildbeschreibung anzeigen zu lassen:

```
if($this->_jg_config->get('jg_show_description_in_popup') == 2)
{
  $data_title .= htmlspecialchars(strip_tags($image->imgtext));
}
  else
{
  $data_title .= htmlspecialchars($image->imgtext);
}
```

**Comment by Erftralle** [comment]
Vielen Dank für den Vorschlag :+1: .
Ich habe ihn gleich eingebaut und eine neue Version veröffentlicht.

**Comment by MrMusic** [comment]
Vielen Dank! :smile:
